name: registry-options
version: 0.2.0.0
synopsis: application options parsing

description: This library provides various parsers for assembling application options

extra-source-files: README.md

category: Data

license: MIT
license-file: LICENSE.txt

maintainer: etorreborre@yahoo.com
git: https://github.com/etorreborre/registry-options

ghc-options: -Wall
  -Wcompat
  -Wincomplete-record-updates
  -fhide-source-paths
  -fprint-potential-instances
  -fno-warn-partial-type-signatures
  -optP-Wno-nonportable-include-path

language: GHC2021

default-extensions:
  - DefaultSignatures
  - DerivingStrategies
  - DerivingVia
  - FunctionalDependencies
  - GADTs
  - LambdaCase
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - StrictData
  - TemplateHaskell
  - TypeFamilies
  - TypeFamilyDependencies

dependencies:
  - base                 >= 4.7   && < 5
  - boxes                >= 0.1   && < 1
  - containers           >= 0.2   && < 1
  - bytestring           >= 0.10  && < 1
  - HsYAML               >= 0.2   && < 1
  - multimap             >= 1.2   && < 2
  - protolude            >= 0.3   && < 0.4
  - registry             >= 0.4   && < 1
  - template-haskell     >= 2.13  && < 3.0
  - text                 >= 1     && < 2
  - transformers         >= 0.5   && < 2
  - th-lift              >= 0.8   && < 1
  - unordered-containers >= 0.2   && < 1
  - vector               >= 0.1   && < 1

library:
  source-dirs: src

  ghc-options: -Wincomplete-uni-patterns

tests:
  spec:
    main: test.hs
    source-dirs:
      - test
    dependencies:
      - registry-options
      - hedgehog
      - registry-hedgehog
      - directory
      - tasty
      - time

    ghc-options: -threaded
      -rtsopts
      -with-rtsopts=-N
      -fno-warn-orphans
      -fno-warn-missing-signatures
      -fno-warn-incomplete-uni-patterns
      -fno-warn-type-defaults
      -optP-Wno-nonportable-include-path
